modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="create_overpowered"
version="2.3"
displayName="Create Overpowered"
displayURL="https://mcreator.net"
credits="Milkman-creator"
authors="Milkman"
description="Create Overpowered is a addon to create adding overpowered things"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_overpowered]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration